
/*
 * 
 */

package mvn.tgBot.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.2.7
 * Sat Feb 13 14:25:49 MSK 2016
 * Generated source version: 2.2.7
 * 
 */


@WebServiceClient(name = "ExtPartyInterface", 
                  wsdlLocation = "https://tstrp.tinkoffinsurance.ru:23001/toi/partners/quotesub/v1.0?wsdl",
                  targetNamespace = "http://toi.ru/esb/services/3rdparty") 
public class ExtPartyInterface_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://toi.ru/esb/services/3rdparty", "ExtPartyInterface");
    public final static QName ExtPartyInterfaceSOAP = new QName("http://toi.ru/esb/services/3rdparty", "ExtPartyInterfaceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("https://tstrp.tinkoffinsurance.ru:23001/toi/partners/quotesub/v1.0?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from https://tstrp.tinkoffinsurance.ru:23001/toi/partners/quotesub/v1.0?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ExtPartyInterface_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExtPartyInterface_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExtPartyInterface_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ExtPartyInterface
     */
    @WebEndpoint(name = "ExtPartyInterfaceSOAP")
    public ExtPartyInterface getExtPartyInterfaceSOAP() {
        return super.getPort(ExtPartyInterfaceSOAP, ExtPartyInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExtPartyInterface
     */
    @WebEndpoint(name = "ExtPartyInterfaceSOAP")
    public ExtPartyInterface getExtPartyInterfaceSOAP(WebServiceFeature... features) {
        return super.getPort(ExtPartyInterfaceSOAP, ExtPartyInterface.class, features);
    }

}
