tg:
    url: https://api.telegram.org
    bot: bot1xxxxxxxx9
    token: AAGxxxxxxxxxxxxxxxxxxxc9o
    cron: '*/3 * * * * *'
db:
    create: false
    name: trip1
soap:
    user: telegram
    password: qxxxxxxxxE
    wsdl: xxxxxxxxSoap-test.wsdl
    prodName: xxxxxxxxxxxxxx
spring:
 data:
  mongodb:
   uri: mongodb://localhost:27017/trip1

abbyy:
    url: http://cloud.ocrsdk.com
    applicationId: TelegramBot
    password: HxxxxxxxxxxxxxxxS+


vitaly: 1xxxxxxxx6
configName: InternalConfig                       f